routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/


Route::post('/odjava','TestController@odjava')->name('odjava');
Route::get('/prijava','TestController@prijava')->name('prijava');

/*
|--------------------------------------------------------------------------
| Order Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('order','OrderController'); //CRUD Route
Route::post('/order/import','OrderController@importCsvData')->name('import.orders');//Importanje csv datoteke

/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| Operation Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('operation','OperationController'); //CRUD Route
Route::get('operation/new/video/{id}','OperationController@addVideoForm')->name('new.video.form');
Route::post('operation/new/video/save','OperationController@storeVideo')->name('store.new.video');

/*--------------------------------------------------------------------------*/



/*
|--------------------------------------------------------------------------
| Video Routes
|--------------------------------------------------------------------------
|
*/
Route::get('operation/new/video/{id}','OperationController@addVideoForm')->name('new.video.form');
Route::post('operation/new/video/save','OperationController@storeVideo')->name('store.new.video');

Route::put('operation/video/update','OperationController@updateVideo')->name('video.update');
Route::delete('operation/delete/vi/deo/{id}','OperationController@deleteVideo')->name('video.destroy');
/*--------------------------------------------------------------------------*/


/*
|--------------------------------------------------------------------------
| Document Routes
|--------------------------------------------------------------------------
|
*/
Route::post('operation/doc/store','OperationController@storeDoc')->name('doc.store');
Route::delete('operation/doc/delete/{id}','OperationController@deleteDoc')->name('doc.destroy');

/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| Workstation Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('radnaStanica', 'RadnaStanicaController');
Route::get('postaviRadnuStanicu/set','RadnaStanicaController@setCookie')->name('setRS');
Route::get('postaviRadnuStanicu/remove/{id}','RadnaStanicaController@removeRS')->name('removeRS'); //removeRS
Route::get('postaviRadnuStanicu/get','RadnaStanicaController@getCookie')->name('getRS');
Route::get('radnaStanica/import/data','RadnaStanicaController@ShowImportForm')->name('import.radnaStanica.form');
Route::post('radnaStanica/import/data/csvData','RadnaStanicaController@ImportCsvData')->name('importRadnaStanica.csv');


/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| Users Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('radnici','RadnikController');
Route::get('radnici/import/data','RadnikController@ShowImportForm')->name('import.form');
Route::post('radnici/import/data/csvData','RadnikController@ImportCsvData')->name('import.csv');
Route::get('postavi/radnika','RadnikController@postavi')->name('setAdmin');
Route::get('izbrisi/radnika','RadnikController@izbrisi')->name('delAdmin');

/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| User view Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('radnikView', 'RadnikViewController');
Route::resource('time','StatistikaController');
Route::post('/reset','StatistikaController@reset')->name('time.reset');
Route::get('radnik/operacija', 'RadnikViewController@showOperation')->name('operation.get');
Route::get('/statistika/order/','StatistikaController@dowload')->name('statistika.dowload');
/*--------------------------------------------------------------------------*/


/*
|--------------------------------------------------------------------------
| Gantrogram view Routes
|--------------------------------------------------------------------------
|
*/
Route::get('/gantogram','GantogramController@index')->name('gantogram.index');
/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| Statistka  Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('/statistka','StatistikaController');
/*--------------------------------------------------------------------------*/

app/RadnaStanica.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class RadnaStanica extends Model
{

    public function NOTavailable(){
        $this->available=false;
        $this->update();
    }

    public function available(){
        $this->available=true;
        $this->update();
    }

    public function setCookie(){
        $this->cookie=true;
        $this->update();
    }

    public function unsetCookie(){
        $this->cookie=false;
        $this->update();
    }

    protected $fillable = ['broj', 'opis','cookie'];
}

app/Http/Controllers/RadnaStanicaController.php
<?php

namespace App\Http\Controllers;

use App\RadnaStanica;
use Cookie;
use Illuminate\Support\Facades\Storage;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Rap2hpoutre\FastExcel\FastExcel;
use Validator;
use File;
use Response;

class RadnaStanicaController extends Controller
{

    public function ShowImportForm()
    {
        return view('backend.radnaStanica.import');
    }

    public function ImportCsvData(Request $request)
    {

        if ($request->file('dat') != null) {


            $file = $request->file('dat');

            // File Details
            $filename = $file->getClientOriginalName();
            $extension = $file->getClientOriginalExtension();
            $tempPath = $file->getRealPath();
            $fileSize = $file->getSize();
            $mimeType = $file->getMimeType();

            // Valid File Extensions
            $valid_extension = array("csv");

            // 2GB in Bytes
            $maxFileSize = 20971520;

            // Check file extension
            if (in_array(strtolower($extension), $valid_extension)) {

                // Check file size
                if ($fileSize <= $maxFileSize) {

                    // File upload location
                    $location ='storage\\tmp';

                    // Upload file
                    $file->move($location, $filename);

                    // Import CSV to Database
                    $filepath = public_path($location . "\\" . $filename);

                    // Reading file
                    $file = fopen($filepath, "r");



                 $collection = (new FastExcel)->import($filepath);
                 fclose($file);

                File::delete($filepath);





                    foreach ($collection as $radnaStanica) {
                        $validator = Validator::make($radnaStanica, ['broj' => 'bail|unique:radna_stanicas',
                                                                      'opis'=>'required|max:255|min:4']);

                        if ($validator->fails()) {

                            if(isset($radnaStanica['broj'])){

                            session()->flash('error', 'Radna stanica '.$radnaStanica['broj'].' već postoji, isptavite csv datoteku');
                            return redirect()->route('import.radnaStanica.form');
                            }
                            else{

                                session()->flash('error', 'Csv datoteka nije valjana');
                                return redirect()->route('import.radnaStanica.form');
                            }

                        } else {


                            try {

                                RadnaStanica::create($radnaStanica);
                            } catch (QueryException $ex) {

                                session()->flash('error', 'Struktura datoteke nije valjana ');
                                return redirect()->route('import.radnaStanica.form');

                            }

                        }

                    }
                    session()->flash('sucess', 'Uspješno !');
                    return redirect()->route('radnaStanica.index');

                }
            }

            session()->flash('error', 'ne valja ektenzija');
            return redirect()->route('import.radnaStanica.form');
        }

        session()->flash('error', 'Učitajte datoteku');
        return redirect()->route('import.radnaStanica.form');
    }

    public function setCookie(Request $request)
    {

        if (Cookie::get($request->radnaStanica_broj) == null) {

            $minutes = 99999999;
            $response = new Response();
            $cookie = cookie($request->radnaStanica_broj, $request->radnaStanica_id, $minutes);
            $radnaStanica = RadnaStanica::find($request->radnaStanica_id);
            $radnaStanica->setCookie();

            return redirect()->route('radnaStanica.edit', $request->radnaStanica_id)->withCookie($cookie);

        }
        return redirect()->route('radnaStanica.edit', $request->radnaStanica_id)->withCookie($cookie);

    }

    public function getCookie(Request $request)
    {
        return $request;
        $value = $request->cookie('setRadnaStanica1');
        echo $value;
    }

    public function index()
    {
        $radneStanice = radnaStanica::orderBy('cookie', 'asc')->get();
        return view('backend.radnaStanica.show', compact('radneStanice'));
    }

    public function create()
    {
        return view('backend.radnaStanica.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'broj' => 'bail|required|unique:radna_stanicas|max:255',
            'opis' => 'required|max:255',
        ]);

        RadnaStanica::create($request->all());

        session()->flash('sucess', 'Uspješno dodana radna stanica !');
        return redirect()->route('radnaStanica.index');

    }

    public function show(RadnaStanica $radnaStanica)
    {
        //
    }

    public function edit($id)
    {
        $radneStanice = RadnaStanica::all();
        $radnaStanica = RadnaStanica::find($id);
        return view('backend.radnaStanica.edit', compact('radnaStanica', 'radneStanice'));
    }

    public function update(Request $request, $id)
    {
        RadnaStanica::where('id', $id)->update($request->except(['_token', '_method']));
        $radneStanice = RadnaStanica::orderBy('broj', 'asc')->get();
        return view('backend.radnaStanica.show', compact('radneStanice'));
    }
    public function removeRS($id){
        $radnaStanica = RadnaStanica::find($id);
        $broj = $radnaStanica->broj;
        $radnaStanica->unsetCookie();

        $radneStanice = radnaStanica::orderBy('broj', 'asc')->get();

        return redirect()->route('radnaStanica.index')->cookie(cookie()->forget($broj));

    }
    public function destroy($id)
    {

        $radnaStanica = RadnaStanica::find($id);
        $broj = $radnaStanica->broj;
        $radnaStanica->delete();

        $radneStanice = radnaStanica::orderBy('broj', 'asc')->get();

        return redirect()->route('radnaStanica.index')->cookie(cookie()->forget($broj));

    }
}

resources/views/backend/radnaStanica/create.blade.php
@extends('backend.layout.layout')

@section('content')
<div class="col-10 col-s-10 menu background">
        <div class="row">
            <div class="col-h3">
                <h2>Nova Radna Stanica</h2>
            </div>
        </div>
        <div class="row">
            <form id="form" action="{{route('radnaStanica.store')}}" method="POST"  enctype="multipart/form-data">
                @csrf


                <div class="row">
                  <div class="col-25">
                    <label for="fname">Broj</label>
                  </div>
                  <div class="col-8">
                    <input type="text" id="broj" name="broj">
                    <small class="small">
                            @if($errors->has('broj'))
                            <div class="alert alert-success">
                              {{$errors->first('broj')}}
                            </div>
                            @endif

                    </small>
                  </div>
                </div>
                <div class="row">
                        <div class="col-25">
                          <label for="subject">Opis Radne Stanice</label>
                        </div>
                        <div class="col-75">
                          <textarea id="opis" name="opis" style="height:200px"></textarea>
                          <small class="small">
                                  @if($errors->has('opis'))
                                  <div class="alert alert-success">
                                    {{$errors->first('opis')}}
                                  </div>
                                  @endif
                          </small>
                      </div>
                      </div>


                      </div>
                      <div class="row">
                            <div class="col-12">
                          <input class="btn bs" type="submit" value="Spremi">
                            </div>
                        </div>
            </form>
        </div>
</div>
@endsection

resources/views/backend/radnaStanica/edit.blade.php
@extends('backend.layout.layout')

@section('content')
<div class="col-10 col-s-10 menu background">
        <div class="row">
            <div class="col-h3">
                <h2>Radna Stanica: <br>{{$radnaStanica->broj}}</h2>
                @if ($radnaStanica->cookie)
                <h1>Postavljena</h1>
                @endif
            </div>
        </div>
        <div class="row">
            <form id="form" action="{{route('radnaStanica.update',$radnaStanica->id)}}" method="POST"  enctype="multipart/form-data">
                @csrf
                @method('PUT')

                <div class="row">
                  <div class="col-25">
                    <label for="fname">Broj</label>
                  </div>
                  <div class="col-8">
                  <input type="text" id="broj" name="broj" value="{{$radnaStanica->broj}}">
                    <small class="small">
                            @if($errors->has('broj'))
                            <div class="error">
                              {{$errors->first('broj')}}
                            </div>
                            @endif

                    </small>
                  </div>
                </div>
                <div class="row">
                        <div class="col-25">
                          <label >Opis radne stanice</label>
                        </div>
                        <div class="col-75">
                        <textarea id="opis" name="opis"  style="height:200px">{{$radnaStanica->opis}}</textarea>
                          <small class="small">
                                  @if($errors->has('opis'))
                                  <div class="error">
                                    {{$errors->first('opis')}}
                                  </div>
                                  @endif
                          </small>
                      </div>
                      </div>



                      </div>
                      <div class="row">
                            <div class="col-12">
                          <input class="btn bs" type="submit" value="Spremi">
                            </div>
                        </div>
                    </form>
                    <?php $stanje=false; $broj=00; ?>

                    @foreach($radneStanice as $item)
                    @if(Cookie::get($item->broj))
                    <?php $stanje=true;$broj=$item->broj ?>
                    @break
                    @else
                    <?php $stanje=false; ?>
                    @endif
                    @endforeach


                    @if(Cookie::get($radnaStanica->broj) == null )
                    @if(!$radnaStanica->cookie)

                    @if($stanje)
                    <h3>Ovo računalo je dodjeljeno radnoj stanici {{$broj}}</h3>
                    @else
                    <form id="myForm" action="{{route('setRS')}}" method="GET"  enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-12">
                          <input class="btn bs" type="button" onclick="submitForm()"  value="Postavi ovo računalo kao radnu stanicu {{$radnaStanica->broj}}">
                            <input type="hidden" name="radnaStanica_id" value="{{$radnaStanica->id}}"/>
                            <input type="hidden" name="radnaStanica_broj" value="{{$radnaStanica->broj}}"/>
                            </div>
                        </div>
                    </form>
                    @endif



                    @endif
                    @endif

                    @if (Cookie::get($radnaStanica->broj) !== null)
                    <form id="myForm" action="{{route('removeRS', $radnaStanica->id)}}" method="GET"  enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-12">
                          <input class="btn bd" type="button" onclick="submitForm()"  value="Izbriši ovo računalo kao radnu stanicu {{$radnaStanica->broj}}">
                            </div>
                        </div>
                    </form>
                    @endif
        </div>
</div>
@endsection

@section('script')

function submitForm(){

    document.getElementById("myForm").submit();
}


@endsection

resources/views/backend/radnaStanica/import.blade.php
@extends('backend.layout.layout')

@section('content')
<div class="col-10 col-s-12 import">

<div class="row message-row">
        <div class="col-10 col-s-12">
@if(session('error'))
<span class="error">{{session('error')}}</span>
@endif
        </div>
</div>

<div class="row">
<div class="col-12 col-s-12">
    <h4 style="text-align:left">Učitaj csv datoteku radnih stanica</h4>
<form method='post' action='{{route('importRadnaStanica.csv')}}' enctype='multipart/form-data'>
    {{ csrf_field() }}
    <input type='file' name='dat' accept=".xls, .csv"  requred >
    <input type='submit' name='submit' value='Import'>
  </form>
</div>
</div>
</div>
@endsection

resources/views/backend/radnaStanica/show.blade.php
<!--RADNE STANICE view-->
@extends('backend.layout.layout')
@section('content')
<div class="col-10 col-s-12">
    <div class="row">
            <div class="col-3 col-s-2">
            <a href="{{route('radnaStanica.create')}}" class="btn bs navButton">Nova radna stanica</a></td>
            </div>

            <div class="col-3 col-s-2">
                <a href="{{route('import.radnaStanica.form')}}" class="btn bs navButton">Import csv datoteku</a></td>
            </div>
            <div class="col-4  col-s-3"><h1></h1></div>
            <div class="col-4  col-s-3"><h1></h1></div>
            <div class="col-4  col-s-3">
                <?php $flag=false; ?>
                    @foreach($radneStanice as $radnaStanica)
                    @if(Cookie::get($radnaStanica->broj))
                  <h3  style="border:solid; padding:1px navButton">Radna stanica<br> {{$radnaStanica->broj}}</h3>
                  <?php $flag=true; ?>
                  @else
                  @endif
                    @endforeach
                    @if($flag==false)
                    <h4  style="border:solid; padding:1px navButton">Ovo računalo nije postavljeno kao radna stanica</h4>
                    @endif
            </div>
        </div>
        <div class="row">
            @if(session()->has('sucess'))
            <span class="success">
                {{ session()->get('sucess') }}
            </span>
            @endif

        @if(session()->has('error'))
            <span class="error">
                {{ session()->get('error') }}
            </span>
        @endif
        </div>
</div>
    <div class="col-10 col-s-12">
        <table>
            <thead>
              <tr>
                <th scope="col">Broj</th>
                <th scope="col">Opis</th>
                <th scope="col">Status</th>
                <th scope="col"></th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              @foreach($radneStanice as $radnaStanica)
              <tr>
                <td>{{$radnaStanica->broj}}</td>
                <td>{{$radnaStanica->opis}}</td>

                @if($radnaStanica->cookie)
                <td style="color:red">Dodijeljena</td>
                @else
                <td><b style="color:green">Slobodna</b></td>
                @endif

                <td>
                @if(Cookie::get($radnaStanica->broj) || !$radnaStanica->cookie)
                  <form action="{{ route('radnaStanica.destroy', $radnaStanica->id)}}" method="post">
                      @csrf
                      @method('DELETE')
                      <button class="btn bd" type="submit">Izbriši</button>
                   </form>
                   @endif
                </td>
                <td>
                    @if(Cookie::get($radnaStanica->broj) || !$radnaStanica->cookie)
                    <a href="{{route('radnaStanica.edit',$radnaStanica->id)}}" class="btn bs">Uredi</a>
                    @endif
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
  </div>
  </div>
@endsection