routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/


Route::post('/odjava','TestController@odjava')->name('odjava');
Route::get('/prijava','TestController@prijava')->name('prijava');

/*
|--------------------------------------------------------------------------
| Order Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('order','OrderController'); //CRUD Route
Route::post('/order/import','OrderController@importCsvData')->name('import.orders');//Importanje csv datoteke

/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| Operation Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('operation','OperationController'); //CRUD Route
Route::get('operation/new/video/{id}','OperationController@addVideoForm')->name('new.video.form');
Route::post('operation/new/video/save','OperationController@storeVideo')->name('store.new.video');

/*--------------------------------------------------------------------------*/



/*
|--------------------------------------------------------------------------
| Video Routes
|--------------------------------------------------------------------------
|
*/
Route::get('operation/new/video/{id}','OperationController@addVideoForm')->name('new.video.form');
Route::post('operation/new/video/save','OperationController@storeVideo')->name('store.new.video');

Route::put('operation/video/update','OperationController@updateVideo')->name('video.update');
Route::delete('operation/delete/vi/deo/{id}','OperationController@deleteVideo')->name('video.destroy');
/*--------------------------------------------------------------------------*/


/*
|--------------------------------------------------------------------------
| Document Routes
|--------------------------------------------------------------------------
|
*/
Route::post('operation/doc/store','OperationController@storeDoc')->name('doc.store');
Route::delete('operation/doc/delete/{id}','OperationController@deleteDoc')->name('doc.destroy');

/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| Workstation Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('radnaStanica', 'RadnaStanicaController');
Route::get('postaviRadnuStanicu/set','RadnaStanicaController@setCookie')->name('setRS');
Route::get('postaviRadnuStanicu/remove/{id}','RadnaStanicaController@removeRS')->name('removeRS'); //removeRS
Route::get('postaviRadnuStanicu/get','RadnaStanicaController@getCookie')->name('getRS');
Route::get('radnaStanica/import/data','RadnaStanicaController@ShowImportForm')->name('import.radnaStanica.form');
Route::post('radnaStanica/import/data/csvData','RadnaStanicaController@ImportCsvData')->name('importRadnaStanica.csv');


/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| Users Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('radnici','RadnikController');
Route::get('radnici/import/data','RadnikController@ShowImportForm')->name('import.form');
Route::post('radnici/import/data/csvData','RadnikController@ImportCsvData')->name('import.csv');
Route::get('postavi/radnika','RadnikController@postavi')->name('setAdmin');
Route::get('izbrisi/radnika','RadnikController@izbrisi')->name('delAdmin');

/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| User view Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('radnikView', 'RadnikViewController');
Route::resource('time','StatistikaController');
Route::post('/reset','StatistikaController@reset')->name('time.reset');
Route::get('radnik/operacija', 'RadnikViewController@showOperation')->name('operation.get');
Route::get('/statistika/order/','StatistikaController@dowload')->name('statistika.dowload');
/*--------------------------------------------------------------------------*/


/*
|--------------------------------------------------------------------------
| Gantrogram view Routes
|--------------------------------------------------------------------------
|
*/
Route::get('/gantogram','GantogramController@index')->name('gantogram.index');
/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| Statistka  Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('/statistka','StatistikaController');
/*--------------------------------------------------------------------------*/

app/Radnik.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;


class Radnik extends User
{

    public function NOTavailable(){
        $this->available=false;
        $this->update();
    }

    public function available(){
        $this->available=true;
        $this->update();
    }




    protected $fillable = ['ime', 'prezime','brojRadnika','rfid'];
}

app/RadnikView.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class RadnikView extends Model
{
    //
}

app/Http/Controllers/RadnikController.php
<?php

namespace App\Http\Controllers;
use Storage;
use Validator;
use App\Radnik;
use Illuminate\Http\Request;
use Cookie;
use Illuminate\Database\QueryException;
use Illuminate\Http\Response;
use Rap2hpoutre\FastExcel\FastExcel;
use Illuminate\Support\Facades\File;


class RadnikController extends Controller
{


    public function izbrisi(Request $request){
        $radnik = Radnik::find($request->id);
        $radnik->isAdmin = false;
        $radnik->save();

        return redirect()->route('radnici.edit', $radnik->id);
    }
    public function postavi(Request $request){
        $radnik = Radnik::find($request->id);
        $radnik->isAdmin = true;
        $radnik->save();

        return redirect()->route('radnici.edit', $radnik->id);
    }



    public function index()
    {
        $radnici=Radnik::all();
        return view('backend.radnik.show',compact('radnici'));
    }



    public function ShowImportForm(){
        return view('backend.radnik.import');
    }

    public function ImportCsvData(Request $request)
    {

        if ($request->file('dat') != null) {


            $file = $request->file('dat');

            // File Details
            $filename = $file->getClientOriginalName();
            $extension = $file->getClientOriginalExtension();
            $tempPath = $file->getRealPath();
            $fileSize = $file->getSize();
            $mimeType = $file->getMimeType();

            // Valid File Extensions
            $valid_extension = array("csv");

            // 2GB in Bytes
            $maxFileSize = 20971520;

            // Check file extension
            if (in_array(strtolower($extension), $valid_extension)) {

                // Check file size
                if ($fileSize <= $maxFileSize) {

                    // File upload location
                    $location ='storage\\tmp';

                    // Upload file
                    $file->move($location, $filename);

                    // Import CSV to Database
                    $filepath = public_path($location . "\\" . $filename);

                    // Reading file
                    $file = fopen($filepath, "r");



                 $collection = (new FastExcel)->import($filepath);
                 fclose($file);

                File::delete($filepath);


                    foreach ($collection as $radnik) {
                        $validator = Validator::make($radnik, ['brojRadnika' => 'required|bail|unique:radniks',
                                                                'ime'=>'required',
                                                                'prezime'=>'required',
                                                                'rfid'=>'required|bail|unique:radniks']);

                        if ($validator->fails()) {


                            if(isset($radnik['brojRadnika'])){

                            session()->flash('error', 'Radnik sa ID-om '.$radnik['brojRadnika'].' već postoji, isptavite csv datoteku');
                            return redirect()->route('import.form');
                            }
                            else{

                                session()->flash('error', 'Csv datoteka nije valjana');
                                return redirect()->route('import.form');
                            }

                        } else {


                            try {

                                radnik::create($radnik);
                            } catch (QueryException $ex) {

                                session()->flash('error', 'Struktura datoteke nije valjana ');
                                return redirect()->route('import.form');

                            }

                        }

                    }
                    session()->flash('sucess', 'Uspješno !');
                    return redirect()->route('radnici.index');

                }
            }

            session()->flash('error', 'ne valja ektenzija');
            return redirect()->route('import.form');
        }

        session()->flash('error', 'Učitajte datoteku');
        return redirect()->route('import.form');
    }








    public function create()
    {
        return view('backend.radnik.create');
    }


    public function store(Request $request)
    {
        Radnik::create($request->all());

        return redirect()->route('radnici.index')->with('success', 'Uspješno dodan radnik');
    }


    public function show(Radnik $radnik)
    {
        //
    }


    public function edit($id)
    {
        $radnik=Radnik::find($id);
        return view('backend.radnik.edit', compact('radnik'));
    }


    public function update(Request $request, $id)
    {

       Radnik::where('id', $id)->update($request->except(['_token','_method']));
       $radnici=Radnik::orderBy('ime','asc')->get();
       return view('backend.radnik.show', compact('radnici'));


    }

    public function destroy($id)
    {
        Radnik::find($id)->delete();
        $radnici=Radnik::orderBy('ime','asc')->get();

        return redirect()->route('radnici.index');


    }
}

resources/views/backend/radnik/create.blade.php
@extends('backend.layout.layout')

@section('content')
<div class="col-10 col-s-10 menu background">
        <div class="row">
            <div class="col-h3">
                <h2>Novi Radnik</h2>
            </div>
        </div>
        <div class="row">
            <form id="form" action="{{route('radnici.store')}}" method="POST"  enctype="multipart/form-data">
                @csrf


                <div class="row">
                  <div class="col-25">
                    <label for="fname">Ime</label>
                  </div>
                  <div class="col-8">
                    <input type="text" id="ime" name="ime">
                    <small class="small">
                            @if($errors->has('ime'))
                            <div class="alert alert-success">
                              {{$errors->first('ime')}}
                            </div>
                            @endif

                    </small>
                  </div>
                </div>


                <div class="row">
                  <div class="col-25">
                    <label for="subject">Prezime</label>
                  </div>
                  <div class="col-8">
                        <input type="text" id="prezime" name="prezime">
                    <small class="small">
                            @if($errors->has('imeOperacije'))
                            <div class="alert alert-success">
                              {{$errors->first('opisOperacije')}}
                            </div>
                            @endif
                    </small>
                </div>
                </div>
                <div class="row">
                        <div class="col-25">
                          <label for="subject">Broj Radnika</label>
                        </div>
                        <div class="col-8">
                              <input type="text" id="ID" name="brojRadnika">
                          <small class="small">
                                  @if($errors->has('imeOperacije'))
                                  <div class="alert alert-success">
                                    {{$errors->first('opisOperacije')}}
                                  </div>
                                  @endif
                          </small>
                      </div>
                      </div>

                      <div class="row">
                        <div class="col-25">
                          <label for="subject">RFID</label>
                        </div>
                        <div class="col-8">
                              <input type="text" id="rfid" name="rfid">
                      </div>
                      </div>

                      <div class="row">
                            <div class="col-12">
                          <input class="btn bs" type="submit" value="Spremi">
                            </div>
                        </div>
            </form>
        </div>
</div>
@endsection

resources/views/backend/radnik/edit.blade.php
@extends('backend.layout.layout')

@section('content')
<div class="col-10 col-s-10 menu background">
        <div class="row">
            <div class="col-h3">
                @if(isset($radnik))
            <h2>Izmjena radnika:<br> {{$radnik->ime}}  {{$radnik->prezime}}  {{$radnik->brojRadnika}}</h2>
            @endif
            </div>
        </div>
        <div class="row">
            <form id="form" action="{{route('radnici.update', $radnik->id)}}" method="POST"  enctype="multipart/form-data">
                @csrf
                @method('PUT')

                <div class="row">
                  <div class="col-25">
                    <label for="fname">Ime</label>
                  </div>
                  <div class="col-8">
                  <input type="text" id="ime" name="ime" value="{{$radnik->ime}}"/>
                    <small class="small">
                            @if($errors->has('ime'))
                            <div class="alert alert-success">
                              {{$errors->first('ime')}}
                            </div>
                            @endif

                    </small>
                  </div>
                </div>


                <div class="row">
                  <div class="col-25">
                    <label for="subject">Prezime</label>
                  </div>
                  <div class="col-8">
                        <input type="text" id="prezime" name="prezime" value="{{$radnik->prezime}}">
                    <small class="small">
                            @if($errors->has('imeOperacije'))
                            <div class="alert alert-success">
                              {{$errors->first('opisOperacije')}}
                            </div>
                            @endif
                    </small>
                </div>
                </div>
                <div class="row">
                        <div class="col-25">
                          <label for="subject">Broj Radnika</label>
                        </div>
                        <div class="col-8">
                              <input type="text" id="ID" name="brojRadnika" value="{{$radnik->brojRadnika}}">
                          <small class="small">
                                  @if($errors->has('imeOperacije'))
                                  <div class="alert alert-success">
                                    {{$errors->first('opisOperacije')}}
                                  </div>
                                  @endif
                          </small>
                      </div>
                      </div>
                      <div class="row">
                            <div class="col-12">
                          <input class="btn bs" type="submit" value="Spremi">
                            </div>
                        </div>
            </form>
            <div class="row">
                    <div class="col-12">
                    <form id="postavi" action="{{route('setAdmin')}}" method="GET">
                        @csrf
                                 <input type="hidden" name="id" value="{{$radnik->id}}">
                                 <input class="btn bs" type="submit" value="Postavi kao poslovođu">
                    </form>

                    </div>
                </div>

                <div class="row">
                        <div class="col-12">
                        <form id="izbrisi" action="{{route('delAdmin')}}" method="GET">
                            @csrf
                                     <input type="hidden" name="id" value="{{$radnik->id}}">
                                     <input class="btn bd" type="submit" value="Postavi kao Montazera">
                        </form>

                        </div>
                    </div>
        </div>
</div>
@endsection

@section('script')
var status = <?php echo $radnik->isAdmin; ?>;
$( ".target" ).hide();
$( ".target" ).hide();
console.log(status);

$( document ).ready(function() {
    $( "#postavi" ).hide();
    $( "#izbrisi" ).hide();

    if(status == 1){
        $( "#izbrisi" ).show();
    }
    else{
        $( "#izbrisi" ).hide();
        $( "#postavi" ).show();
    }
});


@endsection

resources/views/backend/radnik/import.blade.php
@extends('backend.layout.layout')

@section('content')
<div class="col-10 col-s-12 import .full-heigth">

<div class="row message-row">
        <div class="col-10 col-s-12">
@if(session('error'))
<span class="error">{{session('error')}}</span>
@endif
        </div>
</div>

<div class="row">
<div class="col-12 col-s-12">
    <h4 style="text-align:left">Učitaj csv datoteku radnika</h4>
<form method='post' action='{{route('import.csv')}}' enctype='multipart/form-data'>
    {{ csrf_field() }}
    <input type='file' name='dat' accept=".xls, .csv"  requred >
    <input type='submit' class="btn bs" name='submit' value='Import'>
  </form>
</div>
</div>
</div>
@endsection

resources/views/backend/radnik/show.blade.php
@extends('backend.layout.layout')
@section('content')

<div class="col-10 col-s-12">
        <div class="row">
                <div class="col-3 col-s-2">
                <a href="{{route('radnici.create')}}" class="btn bs navButton">Dodaj radnika</a></td>
                </div>

                <div class="col-3 col-s-2">
                    <a href="{{route('import.form')}}" class="btn bs navButton">Import csv</a></td>
                </div>
                <div class="col-3 col-s-6"></div>
            </div>
            <div class="row">
                @if(session()->has('sucess'))
                <span class="success">
                    {{ session()->get('sucess') }}
                </span>
                @endif

            @if(session()->has('error'))
                <span class="error">
                    {{ session()->get('error') }}
                </span>
            @endif
            </div>
    </div>





<div class="col-6 col-s-12">

</div>
    <div class="col-10 col-s-12">
        <table>
            <thead>
              <tr>
                <th scope="col">Ime</th>
                <th scope="col">Prezime</th>
                <th scope="col">ID</th>
                <th scope="col">Status</th>
                <th scope="col"></th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              @foreach($radnici as $radnik)
              <tr>
                <td data-label="Ime">{{$radnik->ime}}</td>
                <td data-label="Prezime">{{$radnik->prezime}}</td>
                <td data-label="ID">{{$radnik->brojRadnika}}</td>
                <td><?php
                if($radnik->isAdmin){
                    echo "Poslovođa";
                }
                else{
                    echo "Montažer";
                }
                ?></td>
                <td>
                  <form action="{{ route('radnici.destroy', $radnik->id)}}" method="post">
                      @csrf
                      @method('DELETE')
                      <button class="btn bd" type="submit">Izbriši</button>
                   </form>
                </td>
                <td><a href="{{route('radnici.edit',$radnik->id)}}" class="btn bs">Uredi</a></td>
              </tr>
              @endforeach
            </tbody>
          </table>
  </div>
  </div>
@endsection