routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/


Route::post('/odjava','TestController@odjava')->name('odjava');
Route::get('/prijava','TestController@prijava')->name('prijava');

/*
|--------------------------------------------------------------------------
| Order Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('order','OrderController'); //CRUD Route
Route::post('/order/import','OrderController@importCsvData')->name('import.orders');//Importanje csv datoteke

/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| Operation Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('operation','OperationController'); //CRUD Route
Route::get('operation/new/video/{id}','OperationController@addVideoForm')->name('new.video.form');
Route::post('operation/new/video/save','OperationController@storeVideo')->name('store.new.video');

/*--------------------------------------------------------------------------*/



/*
|--------------------------------------------------------------------------
| Video Routes
|--------------------------------------------------------------------------
|
*/
Route::get('operation/new/video/{id}','OperationController@addVideoForm')->name('new.video.form');
Route::post('operation/new/video/save','OperationController@storeVideo')->name('store.new.video');

Route::put('operation/video/update','OperationController@updateVideo')->name('video.update');
Route::delete('operation/delete/vi/deo/{id}','OperationController@deleteVideo')->name('video.destroy');
/*--------------------------------------------------------------------------*/


/*
|--------------------------------------------------------------------------
| Document Routes
|--------------------------------------------------------------------------
|
*/
Route::post('operation/doc/store','OperationController@storeDoc')->name('doc.store');
Route::delete('operation/doc/delete/{id}','OperationController@deleteDoc')->name('doc.destroy');

/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| Workstation Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('radnaStanica', 'RadnaStanicaController');
Route::get('postaviRadnuStanicu/set','RadnaStanicaController@setCookie')->name('setRS');
Route::get('postaviRadnuStanicu/remove/{id}','RadnaStanicaController@removeRS')->name('removeRS'); //removeRS
Route::get('postaviRadnuStanicu/get','RadnaStanicaController@getCookie')->name('getRS');
Route::get('radnaStanica/import/data','RadnaStanicaController@ShowImportForm')->name('import.radnaStanica.form');
Route::post('radnaStanica/import/data/csvData','RadnaStanicaController@ImportCsvData')->name('importRadnaStanica.csv');


/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| Users Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('radnici','RadnikController');
Route::get('radnici/import/data','RadnikController@ShowImportForm')->name('import.form');
Route::post('radnici/import/data/csvData','RadnikController@ImportCsvData')->name('import.csv');
Route::get('postavi/radnika','RadnikController@postavi')->name('setAdmin');
Route::get('izbrisi/radnika','RadnikController@izbrisi')->name('delAdmin');

/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| User view Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('radnikView', 'RadnikViewController');
Route::resource('time','StatistikaController');
Route::post('/reset','StatistikaController@reset')->name('time.reset');
Route::get('radnik/operacija', 'RadnikViewController@showOperation')->name('operation.get');
Route::get('/statistika/order/','StatistikaController@dowload')->name('statistika.dowload');
/*--------------------------------------------------------------------------*/


/*
|--------------------------------------------------------------------------
| Gantrogram view Routes
|--------------------------------------------------------------------------
|
*/
Route::get('/gantogram','GantogramController@index')->name('gantogram.index');
/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| Statistka  Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('/statistka','StatistikaController');
/*--------------------------------------------------------------------------*/

app/Operation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Operation extends Model
{




    protected $fillable=['title','description','operation_number','order_id'];
}

app/Http/Controllers/OperationController.php
<?php

namespace App\Http\Controllers;

use App\Doc;
use App\Operation;
use App\Video;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class OperationController extends Controller
{
    public function updateVideo(Request $request)
    {
        $vPath = public_path('Videos');
        $video=Video::find($request->video_id);
        $operation=Operation::findOrFail($video->operation_id);
        File::delete($video->path);

        $videoPath = $request->file('video');
        $video->name = $videoPath->hashName();
        $video->description = $operation->description;
        $video->path = $videoPath->move($vPath, $video->name);
        $video->operation_id = $operation->id;
        $video->user_name_of_video = $videoPath->getClientOriginalName();
        $video->save();



        session()->flash('sucess', 'Uspješnio izmjenjen video');
        return redirect()->route('operation.edit', $operation->id);

    }
    public function deleteVideo($id)
    {

        $video = Video::find($id);
        $operation = Operation::where('id', $video->operation_id)->first();
        File::delete($video->path);
        $docs = Doc::where('video_id', $video->id)->get();

        foreach ($docs as $doc) {
            File::delete($doc->path);
            $doc->delete();
        }
        $video->delete();

        return redirect()->route('operation.edit', $operation->id)->with('success', 'Uspješno izbrisan video');
    }
    public function storeDoc(Request $request)
    {
        $dPath = public_path('Docs');
        $video = Video::findOrFail($request->video);
        $operation = Operation::findOrFail($video->operation_id);

        foreach ($request->file('doc') as $file) {

            $doc = new Doc();
            $docPath = $file;
            $doc->name = $docPath->hashName();
            $doc->description = $operation->description;
            $doc->path = $docPath->move($dPath, $doc->name);
            $doc->video_id = $request->video;
            $doc->user_name_of_doc = $docPath->getClientOriginalName();
            $doc->save();
        }

        return redirect()->route('operation.edit', $operation);

    }
    public function deleteDoc($id)
    {
        Doc::destroy($id);
    }

    /**
     * sore video in db
     *
     * @return \Illuminate\Http\Response
     */
    public function storeVideo(Request $request)
    {

        $i = 0;
        $j = 0;
        $vPath = public_path('Videos');
        $dPath = public_path('Docs');
        $operation = Operation::find($request->operation_id);

        while ($request->file('video' . $i)) {
            $video = new Video();
            $videoPath = $request->file('video' . $i);
            $video->name = $videoPath->hashName();
            $video->description = $operation->description;
            $video->path = $videoPath->move($vPath, $video->name);
            $video->operation_id = $operation->id;
            $video->user_name_of_video = $videoPath->getClientOriginalName();
            $video->save();

            foreach ($request->file('doc' . $i) as $file) {

                $doc = new Doc();
                $docPath = $file;
                $doc->name = $docPath->hashName();
                $doc->description = $operation->description;
                $doc->path = $docPath->move($dPath, $doc->name);
                $doc->video_id = $video->id;
                $doc->user_name_of_doc = $docPath->getClientOriginalName();
                $doc->save();
                $j++;
            }

            $i++;

        }
        return redirect()->route('operation.edit', $operation);
    }

    /**
     * Display new video from.
     *
     * @return \Illuminate\Http\Response
     */
    public function addVideoForm($id)
    {
        $operation = Operation::findOrFail($id);

        return view('backend.operation.newVideo', compact('operation'));
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $operations = Operation::all();

        return view('backend.operation.show', compact('operations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.operation.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // $this->validate($request, [
        //     'operation_number' => 'unique:operations|required',
        //     'title'=>'required',
        //     'description'=>'required|max:255|min:4'

        // ]);

        $i = 0;
        $j = 0;
        $vPath = public_path('Videos');
        $dPath = public_path('Docs');

        $operation = new Operation();
        $operation->title = $request->title;
        $operation->description = $request->description;
        $operation->operation_number = $request->operation_number;
        $operation->save();

        if ($request->file('video' . $i) != null) {

            while ($request->file('video' . $i)) {
                $video = new Video();
                $videoPath = $request->file('video' . $i);
                $video->name = $videoPath->hashName();
                $video->description = $request->description;
                $video->path = $videoPath->move($vPath, $video->name);
                $video->operation_id = $operation->id;
                $video->user_name_of_video = $videoPath->getClientOriginalName();
                $video->save();

                foreach ($request->file('doc' . $i) as $file) {

                    $doc = new Doc();
                    $docPath = $file;
                    $doc->name = $docPath->hashName();
                    $doc->description = $request->description;
                    $doc->path = $docPath->move($dPath, $doc->name);
                    $doc->video_id = $video->id;
                    $doc->user_name_of_doc = $docPath->getClientOriginalName();
                    $doc->save();

                }

                $i++;
            }

            session()->flash('sucess', 'Uspješno dodana operacija ' . $operation->number);
            return redirect()->route('operation.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Operation  $operation
     * @return \Illuminate\Http\Response
     */
    public function show(Operation $operation)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Operation  $operation
     * @return \Illuminate\Http\Response
     */
    public function edit(Operation $operation)
    {

        $videos = Video::where('operation_id', $operation->id)->get();

        $docs = [];

        foreach ($videos as $video) {
            $doc = Doc::where('video_id', $video->id)->get();
            array_push($docs, [$video->id => $doc]);
        }

        return view('backend.operation.edit', compact('operation', 'videos', 'docs'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Operation  $operation
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Operation $operation)
    {

        $operation->update($request->all());

        return redirect()->route('operation.edit', $operation);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Operation  $operation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Operation $operation)
    {
        $number = $operation->number;

        $videos = Video::where('operation_id', $operation->id)->get();
        foreach ($videos as $video) {
            File::delete($video->path);

            $docs = Doc::where('video_id', $video->id)->get();
            foreach ($docs as $doc) {
                File::delete($doc->path);
                $doc->delete();
            }
            $video->delete();
        }
        $operation->delete();

        session()->flash('sucess', 'Uspješno izbrisana operacija ' . $number);
        return redirect()->route('operation.index');
    }
}

resources/views/backend/operation/create.blade.php
@extends('backend.layout.layout')

@section('content')
<div class="col-10 col-s-10 menu background">
        <div class="row">
            <div class="col-h3">
                <h2>Nova operacija</h2>
            </div>
        </div>
        <div class="row">
            <form id="form" action="{{route('operation.store')}}" method="POST"  enctype="multipart/form-data">
                @csrf


                <div class="row">
                  <div class="col-25">
                    <label>Naziv operacije</label>
                  </div>
                  <div class="col-75">
                    <input type="text" name="title" required placeholder="Naziv Operacije"
                    oninvalid="this.setCustomValidity('Unesite naziv Operacije')"
                    oninput="this.setCustomValidity('')"  />
                  </div>
                </div>

                <div class="row">
                    <div class="col-25">
                      <label>Broj operacije</label>
                    </div>
                    <div class="col-75">
                      <input type="text" name="operation_number" required  placeholder="npr. 1"
                      oninvalid="this.setCustomValidity('Unesite broj Operacije')"
                      oninput="this.setCustomValidity('')"  />
                    </div>
                  </div>

                <div class="row">
                  <div class="col-25">
                    <label>Opis operacije</label>
                  </div>
                  <div class="col-75">
                    <textarea name="description" placeholder="Opis se odonosi na video i dokument" style="height:200px" required placeholder="Naziv Operacije"
                    oninvalid="this.setCustomValidity('Unesite opis operacije')"
                    oninput="this.setCustomValidity('')"></textarea>
                   </div>
                </div>


    <div class="row b2"id="dynamic_field">
                <div class="row">

                <div class="col-3"></div>



                <div class="col-25">


                <div class="row">
                        <label class="custom-file-upload">
                                <i class="fa fa-cloud-upload"></i>Dodaj Video
                              </label>
                </div>
                <div class="row">
                <input type="file" id="video0" name="video0"  accept="video/*" >
                </div>
                </div>



                <div class="col-25">

                    <div class="row">
                            <label class="custom-file-upload">
                                    <i class="fa fa-cloud-upload"></i>Dodaj Dokument(e)
                                  </label>
                    </div>
                    <div class="row">
                                  <input  type="file"  id="doc0" name="doc0[]" accept=".pdf,.doc,.docx" multiple >
                    </div>
                </div>
                    <div class="col-2">
                    <input class="btn bs" id="add"  type="button" value="+">
                    </div>

                </div>
                <!--KRAJ PRVI RED-->
<!--Drugi red ..-->

    </div>
            </div>
            <div class="row">
                    <div class="col-2">
                  <input class="btn bs" type="submit" value="Spremi">
                    </div>
                </div>

</form>

</div>
@endsection
@section('script')
$(document).ready(function(){
    var postURL = "<?php echo url('addmore'); ?>";
    var i=0;


    $('#add').click(function(){
         i++;

         var appendME='<div class="row b2" id="row'+i+'">'+
         '<div class="col-3"></div>'+
         '<div class="col-25">'+
         '<div class="row">'+
        '<label>Video</label>'+
         '</div>'+
         '<div class="row">'+
         '<input type="file" id="video'+i+'" name="video'+i+'"  accept="video/*" >'+
         '</div>'+
         '</div>'+
         '<div class="col-25">'+
             '<div class="row">'+
            '<label>Dokument</label>'+
             '</div>'+
             '<div class="row">'+
                     '<input  type="file"  id="doc'+i+'" name="doc'+i+'[]" accept=".pdf,.doc,.docx" multiple >'+
                    '</div>'+
                '</div>'+
                '<div class="col-2">'+
                '<input class="btn bd btn_remove" id="'+i+'"  type="button" value="-">'+
                '</div>'+

            '</div>';

         $('#dynamic_field').append(appendME);
 });


    $(document).on('click', '.btn_remove', function(){
         var button_id = $(this).attr("id");
         $('#row'+button_id+'').remove();
         //alert("kliknut"+button_id+'');
    });

  });


@endsection

resources/views/backend/operation/edit.blade.php
@extends('backend.layout.layout')
@section('content')
<div class="col-12 col-s-10 menu background"><!--COLUMNA FORME-->

    <!--RED NASLOVA-->
    <div class="row">
        <div class="col-h3">
        <h2>Izmjena Operacije:<br> <b>{{$operation->operation_number}}</b></h2>
        </div>
    </div>
<!--KRAJ REDA NASLOVA-->


<!--RED FORME-->
    <div class="row">
        <form id="form" action="{{route('operation.update', $operation)}}" method="POST"  enctype="multipart/form-data">
            @csrf
            @method('PUT')
<!--RED ZA NAZIV OPERACIJE-->
            <div class="row">
              <div class="col-25">
                <label>Naziv operacije</label>
              </div>
              <div class="col-75">
              <input type="text"name="title" value="{{$operation->title}}">
              </div>
            </div>

            <div class="row">
                <div class="col-25">
                  <label>Broj operacije</label>
                </div>
                <div class="col-75">
                <input type="text"  name="operation_number" value="{{$operation->operation_number}}">
                </div>
              </div>
<!--KRAJ REDA ZA NAZIV OPERACIJE-->
<!--RED ZA OPIS OPERACIJE-->
            <div class="row">
              <div class="col-25">
                <label class="label">Opis operacije</label>
              </div>
              <div class="col-75">
              <textarea name="description" placeholder="Opis se odonosi na video i doc" style="height:200px">{{$operation->description}}</textarea>
            </div>
            </div>
            <div class="row">
            <div class="col-4">
                <div class="row">
                <input class="btn bs" type="submit" value="Spremi"><!--SPREMI BUTTON TJ ROW-->
            </div>
            </div>
                <div class="col-4">
                        <div class="row">
                       <a href="{{route('new.video.form', $operation->id)}}" class="btn bs">Dodaj Video</a>
                        </div>
                </div>
            </div>
        </div>
        </form>
<!--KRAJ REDA ZA OPIS OPERACIJE-->

<!--RED ZA VIDEO I docE-->
@foreach($videos as $video)
<div class="row"><hr class="hrborder"></div>

<div class="row">



    <!--COLUMNA ZA VIDEO-->
<div class="col-6"  >
            <!--RED ZA VIDEO PLAYER-->
            <div class="row">
                <video controls width="100%" height="100%"  muted>
                <source src={{asset('Videos\\'.$video->name)}} type="video/mp4">
                  </video>
            </div>
            <!--KRAJ REDA ZA VIDEO PLAYER-->
            <div class="row">
            <div class="col-4 col-s-2">
            <button type="button" idVideo="{{$video->id}}" class="btn bd video" videoToken="{{ csrf_token() }}" >Izbriši Video</button>
            </div>

            <div class="col-4 col-s-3">
            <form enctype="multipart/form-data" action="{{route('video.update', $video->id)}}" method="POST"   id="colVideo-{{$video->id}}" onchange="getid(this.id)">
                @csrf
                @method('PUT')
                    <label  class="btn bs">
                    <input  name="video"  accept="video/*"  id="{{$video->id}}" type="file" style="display:none" class=" btn bs video_attachment addbut" />
                           Izmjeni Video
                    <input type="hidden" name="operation_id" value="{{$operation->id}}"/>
                    <input type="hidden" name="video_id" value="{{$video->id}}"/>
                    </label>
                    <label class="countVideo"></label>
                <input type="submit" class="btn bs save-video" id="savevideo-{{$video->id}}" value="Spremi Promjene Videa">
            </form>
            </div>
        </div>
    </div>
            <!--KRAJ COLUMNE ZA VIDEO-->


            <!--COLUMNA ZA POPIS DOKUMENATA-->
            <div class="col-5">
                <div class="row">
                @foreach ($docs as $doc)
                <table>
                        <tbody>
                @foreach($doc as $item)
                @for($i=0;$i<count($item);$i++)
                @if($item[$i]->video_id == $video->id)
                          <tr>
                            <td>{{$item[$i]->user_name_of_doc}}</td>
                            <td></td>
                            <td>
                            <button type="button" iddoc="{{$item[$i]->id}}" class="btn bd doc" docToken="{{ csrf_token() }}" >Izbriši</button>
                            </td>
                          </tr>
                          @endif
                @endfor
                @endforeach
            </tbody>
        </table>
                @endforeach
            </div>
                <div class="row">
                    <br>
                    <div class="col-3"></div>
                    <div class="col-6">
                <form onchange="dgetid(this.id)" id="docID{{$video->id}}" action="{{route('doc.store')}}" method="POST"  enctype="multipart/form-data">
                        @csrf
                            <label  class="btn bs">
                                <input style="display: none"  type="file"  id="doc" name="doc[]" accept=".pdf,.doc,.docx" multiple >
                                Dodaj Dokument
                            </label>
                            <label id="countdoc{{$video->id}}"></label>
                        <input type="submit" class="btn bs" id="save-doc{{$video->id}}" value="Spremi Promjene Dokumenata" />
                        <input type="hidden" name="operacija" value="{{$operation->id}}" />
                        <input type="hidden" name="video" value="{{$video->id}}" />


                    </form>
                    </div>
                    </div>
                </div>
            <!--KRAJ KOLUMNE ZA POPIS docE-->
            </div>
        <!--KRAJ REDA ZA VIDEO I OPERACIJE-->

<!--KRAJ REDA FORME-->
@endforeach
<!--KRAJ REDA ZA VIDEO I OPERACIJE-->

</form>
<!--KRAJ FORME-->
</div>
</div>
<!--KRAJ COLUMNE ZA FORMU--> --}}
@endsection


 @section('script')

$(document).ready(function(){
@foreach ($videos as $video)
var filesV = $("[name='video']").prop("files");
   if(filesV.length <= 0){
   $("#savevideo-{{$video->id}}").hide();
    }

    var filesD = $("[name='doc[]']").prop("files");
    if(filesD.length==0){
        $("#save-doc{{$video->id}}").hide();
   }


@endforeach

 });


function getid(id){
    var filesV = $("[name='video']").prop("files");
    var numb = id.match(/\d/g);
    numb = numb.join("");

    $("#savevideo-"+numb).show();
    $('.countVideo').append('Novi video učitan');
}

function dgetid(id){


var realID = id.replace('docID','');
var numb = id.match(/\d/g);
numb = numb.join("");

var filesD = $("[name='doc[]']").prop("files");

         $('#countdoc'+realID).empty();
       $('#countdoc'+realID).append('Dodani dokument(i)');
     $("#save-doc"+numb).show();

}


    function getFile(){
        document.getElementById("doc").click();
   }


   //BUTTON ZA BRISANJE
   $(document).on('click', ".doc", function() {
    var iddoc=$(this).attr('iddoc');
    var docToken = $(this).attr("docToken");

    var url = '{{route("doc.destroy","id")}}';
    url = url.replace('id', iddoc);

    $.ajax({
        type: 'POST',
        url: url,
        data: {
            _method:"DELETE",
            'id' : iddoc
        },
        headers: { 'X-CSRF-TOKEN' : docToken },
        success: function(response) {
            console.log("work");
            location.reload();
        }

   });
});

$(document).on('click', ".video", function() {
    console.log("video ajax");
    var idVideo=$(this).attr('idVIdeo');
    var videoToken = $(this).attr("videoToken");

    var url = '{{route("video.destroy","id")}}';
    url = url.replace('id', idVideo);
    console.log(idVideo);

    $.ajax({
        type: 'POST',
        url: url,
        data: {
            _method:"DELETE",
            'id' : idVideo
        },
       headers: { 'X-CSRF-TOKEN' : videoToken },
        success: function(response) {
            console.log("work video ajax");
            location.reload();
        }

   });

});
@endsection

resources/views/backend/operation/layout.blade.php
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{{ asset('/css/style.css') }}" rel="stylesheet">
<link href="{{ secure_asset('/css/style.css') }}" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

</head>
<body>

<div class="header">
  <h1>{{ config('app.name') }}</h1>
</div>

<div class="row">
  <div class="col-2 col-s-12 menu">
    <ul>
     <a href="{{route('nalog.index')}}"> <li>Nalozi</li></a>
     <a href="{{route('operacije.index')}}"> <li>Operacije</li></a>
     <a href="{{route('radnici.index')}}"> <li>Radnici</li></a>
     <a href="{{route('radnaStanica.index')}}"> <li>Radne stanice</li></a>
     <a href="{{route('time.index')}}"> <li>Statisitka</li></a>
    </ul>
  </div>
  @yield('content')

</div>
<script>
@yield('script')
</script>
</body>
</html>

resources/views/backend/operation/one.blade.php
@extends('backend.operacije.layout')

@section('content')
testing prikaz jedne operacije
        <div class="col-10 col-s-12">
                <div class="col-4 col-s-12">
                        <div class="col-h3">
                                <h2>Operacija: <br>{{$operacija->imeOperacije}}</h2>
                            </div>
                    </div>
        dodati video i dokumente edit i update...
      </div>


@endsection

resources/views/backend/operation/show.blade.php
@extends('backend.layout.layout')
@section('content')
<div class="col-4 col-s-12">
   <div class="row"> <a href="{{route('operation.create')}}" class="btn bs">Nova operacija</a></td></div>

   @if(session()->has('error'))
<div class="row message-row">
    <div class="col-6"></div>
    <div class="col-6">
            <span class="error">
                    {{ session()->get('error') }}
                </span>
    </div>
</div>
@endif

@if(session()->has('sucess'))
<div class="row message-row">
    <div class="col-3"></div>
    <div class="col-6">
            <span class="sucess">
                    {{ session()->get('sucess') }}
                </span>
    </div>
</div>
@endif
</div>
    <div class="col-12 col-s-12">
        <table>
            <thead style="min-width:10%;">
              <tr>
                <th scope="col">Broj Operacije</th>
                <th scope="col">Ime Operacije</th>
                <th scope="col">Opis</th>
                <th scope="col"></th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              @foreach($operations as $operation)
              <tr>
                <td >{{$operation->operation_number}}</td>
                <td>{{$operation->title}}</td>
                <td >{{$operation->description}}</td>
                <td>
                  <form action="{{ route('operation.destroy', $operation)}}" method="post">
                      @csrf
                      @method('DELETE')
                      <button class="btn bd" type="submit">Izbriši</button>
                   </form>
                </td>
                <td><a href="{{route('operation.edit',$operation->id)}}" class="btn bs">Detalji</a></td>
              </tr>
              @endforeach
            </tbody>
          </table>
  </div>

@endsection

@section('script')
jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
        window.location = $(this).data("href");
    });
});
@endsection