routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/


Route::post('/odjava','TestController@odjava')->name('odjava');
Route::get('/prijava','TestController@prijava')->name('prijava');

/*
|--------------------------------------------------------------------------
| Order Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('order','OrderController'); //CRUD Route
Route::post('/order/import','OrderController@importCsvData')->name('import.orders');//Importanje csv datoteke

/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| Operation Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('operation','OperationController'); //CRUD Route
Route::get('operation/new/video/{id}','OperationController@addVideoForm')->name('new.video.form');
Route::post('operation/new/video/save','OperationController@storeVideo')->name('store.new.video');

/*--------------------------------------------------------------------------*/



/*
|--------------------------------------------------------------------------
| Video Routes
|--------------------------------------------------------------------------
|
*/
Route::get('operation/new/video/{id}','OperationController@addVideoForm')->name('new.video.form');
Route::post('operation/new/video/save','OperationController@storeVideo')->name('store.new.video');

Route::put('operation/video/update','OperationController@updateVideo')->name('video.update');
Route::delete('operation/delete/vi/deo/{id}','OperationController@deleteVideo')->name('video.destroy');
/*--------------------------------------------------------------------------*/


/*
|--------------------------------------------------------------------------
| Document Routes
|--------------------------------------------------------------------------
|
*/
Route::post('operation/doc/store','OperationController@storeDoc')->name('doc.store');
Route::delete('operation/doc/delete/{id}','OperationController@deleteDoc')->name('doc.destroy');

/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| Workstation Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('radnaStanica', 'RadnaStanicaController');
Route::get('postaviRadnuStanicu/set','RadnaStanicaController@setCookie')->name('setRS');
Route::get('postaviRadnuStanicu/remove/{id}','RadnaStanicaController@removeRS')->name('removeRS'); //removeRS
Route::get('postaviRadnuStanicu/get','RadnaStanicaController@getCookie')->name('getRS');
Route::get('radnaStanica/import/data','RadnaStanicaController@ShowImportForm')->name('import.radnaStanica.form');
Route::post('radnaStanica/import/data/csvData','RadnaStanicaController@ImportCsvData')->name('importRadnaStanica.csv');


/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| Users Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('radnici','RadnikController');
Route::get('radnici/import/data','RadnikController@ShowImportForm')->name('import.form');
Route::post('radnici/import/data/csvData','RadnikController@ImportCsvData')->name('import.csv');
Route::get('postavi/radnika','RadnikController@postavi')->name('setAdmin');
Route::get('izbrisi/radnika','RadnikController@izbrisi')->name('delAdmin');

/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| User view Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('radnikView', 'RadnikViewController');
Route::resource('time','StatistikaController');
Route::post('/reset','StatistikaController@reset')->name('time.reset');
Route::get('radnik/operacija', 'RadnikViewController@showOperation')->name('operation.get');
Route::get('/statistika/order/','StatistikaController@dowload')->name('statistika.dowload');
/*--------------------------------------------------------------------------*/


/*
|--------------------------------------------------------------------------
| Gantrogram view Routes
|--------------------------------------------------------------------------
|
*/
Route::get('/gantogram','GantogramController@index')->name('gantogram.index');
/*--------------------------------------------------------------------------*/

/*
|--------------------------------------------------------------------------
| Statistka  Routes
|--------------------------------------------------------------------------
|
*/
Route::resource('/statistka','StatistikaController');
/*--------------------------------------------------------------------------*/

resources/views/backend/layout/layout.blade.php
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{{ asset('/css/style.css') }}" rel="stylesheet">
<link href="{{ secure_asset('/css/style.css') }}" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

</head>
<body>

<div class="header">
    <div class="row">
        <div class="col-4"><h1>LeanFactory <small style="font-size:8pt">AdminPage</small></h1></div>
        <div class="col-1"></div>
        <div class="col-6"></div>
        <div class="col-1">
        <form action="{{route('odjava')}}" method="POST">
            @csrf
                <input type="hidden" name="logout" value="true">
                <h3>Radnik: {{Session::get('radnik')->brojRadnika}}</h3>
                <button type="submit" style="background-color:red;"> <h3 style="display:block">Odjava</h3>
                </button>
            </form>

        </div>
        </div>
</div>

<div class="row">
  <div class="col-3 col-s-12 menu">
    <ul>
     <a  href="{{route('order.index')}}"> <li class="menu-height">Nalozi</li></a>
     <a  href="{{route('operation.index')}}"> <li class="menu-height">Operacije</li></a>
     <a  href="{{route('radnaStanica.index')}}"> <li class="menu-height">Radne stanice</li></a>
     <a href="{{route('radnici.index')}}"> <li class="menu-height">Radnici</li></a>
     <a href="{{route('gantogram.index')}}"> <li class="menu-height">Raspored</li></a>
    <a href="{{route('statistka.index')}}"> <li class="menu-height">Izvoz podataka</li></a>
    </ul>
  </div>
  <div class="col-9 col-s-12">
  @yield('content')
  </div>
</div>
<script>
@yield('script')
</script>
</body>
</html>